spring:
    jpa:
        properties:
            hibernate:
                show_sql: true
    datasource:
        driver: org.postgresql.Driver
        url:  jdbc:postgresql://localhost/nodedb
        username: postgres
        password: 222

xmlfilename: data/RU-NVS.osm.bz2
readcount: 10
