spring:
    jpa:
        properties:
            hibernate:
#                show_sql: true
                jdbc:
                    batch_size:1000
    datasource:
        driver: org.postgresql.Driver
        url:  jdbc:postgresql://localhost/nodedb
        #?useServerPrepStmts=false&rewriteBatchedStatements=true
        username: postgres
        password: 222

xmlfilename: data/RU-NVS.osm.bz2
readcount: 1000

#logging:
#    level:
#        org:
#            hibernate:
#                type:
#                    descriptor:
#                        sql: trace